### ISSUE TITLE
Automated builds for Windows

### ISSUE THREAD

**Issue by SuNNjek** [SuNNjek/rotate-plugin#1]
It would be nice to automatically create DLLs for Windows using a CI solution (preferably GitHub Actions). I don't know whether the plugin even compiles on Windows currently, so this needs to be checked first. If possible, both x86 and x64 versions should be built.

**Comment by BamButz** [comment]
I would do that, you can assign me if you like.

**Comment by SuNNjek** [comment]
Done. I fixed the compilation on Windows yesterday already so that's not an issue anymore.
